### ISSUE TITLE
Are action types currently used for type checking?

### ISSUE THREAD

**Issue by michallepicki** [gfngfn/Sesterl#20]
More than inquiry than an issue, feel free to close.

I tried changing the concurrency example from the Readme, and I was not getting any type errors. E.g. I changed the type (pattern match structure) of msg received with msg, or changed the type of msg sent with send. I even tried changing `let n = 10 in` to `let n = "10" in` and didn't get any errors, just as if presence of `act` on the called function prevented type checking of passed arguments.

I completely understand the project is in early stages, I am just wondering, is there any checking done on the "action types" right now, or will that come later, e.g. when session types are implemented? Thanks!

**Comment by gfngfn** [comment]
> I even tried changing `let n = 10 in` to `let n = "10"` in and didn't get any errors

I couldn't reproduce this problem. The following change is rejected as intended:

```diff
 module Example = struct

   /* dummy */
   val some_heavy_calculation(n) =
     n

   val rec wait_all(msgacc, n) = act
     if n <= 0 then
       return(msgacc)
     else
       receive
       | {pid, msg} ->
           let _ = print_debug(format(f'message ~p received from: ~p~n', {msg, pid})) in
           wait_all(msg :: msgacc, n - 1)
       end

   val rec spawn_all(pidacc, n) = act
     if n <= 0 then
       return(pidacc)
     else
       do parent <- self() in
       do pid <-
         spawn(fun() -> act
           do me <- self() in
           let msg = some_heavy_calculation(n) in
           send(parent, {me, msg})
         end)
       in
       spawn_all(pid :: pidacc, n - 1)

   val main(arg) = act
-    let n = 10 in
+    let n = "10" in
     do pids <- spawn_all([], n) in
     let _ = print_debug(format(f'spawned: ~p~n', {pids})) in
     do msgs <- wait_all([], n) in
     let _ = print_debug(msgs) in
     return({})

 end
```

```console
$ sesterl build example.sest -o _generated/
  parsing '<path/to>/example.sest' ...
  type checking '<path/to>/example.sest' ...
! [Type error] file 'example.sest', line 33, characters 15-24:
  this expression has type
    fun(list<pid<'a>>, int) -> [{pid<'a>, int}]list<pid<'a>>
  but is expected of type
    fun(list<pid<'a>>, binary) -> [{pid<'a>, int}]list<pid<'a>>
```

**Comment by michallepicki** [comment]
I will try again and report back, thanks for checking!

**Comment by michallepicki** [comment]
I must have been running the compiler wrong way somehow, or my editor was playing tricks with me, I am getting errors now!

BTW: WOW this is very cool

**Comment by gfngfn** [comment]
I’m glad to hear that. Thank you anyway for reporting!
