### ISSUE TITLE
Set configuration file name sesterl.yaml instead of package.yaml

### ISSUE THREAD

**Issue by michallepicki** [gfngfn/Sesterl#27]
I saw this on the Projects board. I can work on this chore, I would send PRs to here, rebar_sesterl_plugin and all project repositories. Would that be helpful?

**Comment by gfngfn** [comment]
Yes, that change is welcomed! Slight care should probably be, however, taken as to the following:

- giving correct semantic versions to packages and the compiler, and/or
- keeping the backward compatibility by providing a fallback mechanism.
