### ISSUE TITLE
Arithmetic operators associativity is wrong

### ISSUE THREAD

**Issue by michallepicki** [gfngfn/Sesterl#67]
```
let 1 = 3 - 1 - 1
```

This should work but results in
```
escript: exception error: no match of right hand side value 3
```

**Comment by michallepicki** [comment]
Same with
```
let 8 = 8 / 2 * 2
```
it should work but results in:
```
escript: exception error: no match of right hand side value 2
```

**Comment by gfngfn** [comment]
Thank you for reporting! (and sorry that I haven't been in touch much lately due to engagements in other personal projects or joint work.)

This is another simple mistake of the parser implementation… #68 will solve this. Hmm, I should provide much more tests about the parser…

**Comment by michallepicki** [comment]
No worries, I'm glad I could help finding this and I'm happy I'm learning a bit more about ocaml and menhir :)
